notebook:
  image: scipy-athena:dev
  environment:
    AWS_KEY: ${AWS_KEY}
    AWS_SECRET: ${AWS_SECRET}
    AWS_REGION: ${AWS_REGION}
    AWS_S3_STAGING: ${AWS_S3_STAGING}
  ports:
    - "8888:8888"
  volumes:
    - "/Users/bchan/projects/my_github/athena-python-notebook/jupyter/:/home/jovyan"