notebook:
  image: scipy-athena:dev
  environment:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${AWS_REGION}
    AWS_S3_STAGING: ${AWS_S3_STAGING}
  ports:
    - "8888:8888"
  volumes:
    - "/Users/bchan/projects/my_learning/athena-python-notebook/jupyter/:/home/jovyan"