CREATE EXTERNAL TABLE "stock-price-db"."raw" (
  symbol STRING,
  date STRING,
  open DOUBLE,
  high DOUBLE,
  low DOUBLE,
  close DOUBLE,
  adjusted_close DOUBLE,
  VOLUME BIGINT
) 
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY ','
  ESCAPED BY '\\'
  LINES TERMINATED BY '\n'
LOCATION 's3://YOUR_BUCKET/YOUR_PATH';
